#---
#- hosts: all
#  tasks:
  - name: CONFIGURE YUM REPOSITORY-RHEL
    template: owner=root group=root mode=644
              src=/root/post-install-config/roles/common/templates/UMS-RHEL.repo
              dest=/etc/yum.repos.d/UMS.repo
    when: ansible_distribution == "RedHat" and  ansible_distribution_major_version == "7"      


  - name: CONFIGURE YUM REPOSITORY-CENTOS
    template: owner=root group=root mode=644
              src=/root/post-install-config/roles/common/templates/UMS-CENTOS.repo
              dest=/etc/yum.repos.d/UMS.repo
    when: ansible_distribution == "CentOS" and  ansible_distribution_major_version == "7"